# For more info on HTTP files go to https://aka.ms/vs/httpfile
POST http://localhost:7014/api/KeyGenRequest
Content-Type: application/json
{
  "userName": "testGenName1",
  "apiKey": "5b9cd2eede514baaa7e2f670204ffcf3"
}